### PR TITLE
Create Sandip.md

### PR DESCRIPTION
**Pull request by Wentale**
Created another Persona for VC - Sandip

### CODE REVIEW

**Review by xolotl — APPROVED** [review]
Awesome!

**Comment by xolotl** [comment]
Does it make sense to add Sandip in one or more places in the [directory of personas](../blob/master/personas/index.md)?

**Comment by Wentale** [comment]
The way I [read ](https://mozilla.github.io/open-leadership-training-series/articles/building-communities-of-contributors/bring-on-contributors-using-personas-and-pathways/)it, a single persona could have multiple pathways? Or is it single persona/pathway?

**Comment by xolotl** [comment]
For sure! One persona might well take many pathways, just as you and I have ;)

**Comment by Wentale** [comment]
I think the [directory of personas](https://github.com/virtuallyconnecting/vc/blob/master/personas/index.md) should list Kelly and Sandip. At the moment it is listing Pathways??

**Comment by xolotl** [comment]
I see Kelly. But yes Sandip should be there too.

**Pull request merged**
