### PR TITLE
Update LICENSE.md - new language about VC brand

### PR DESCRIPTION
**Pull request by murphyjoe**
First stab of some language to say that we'd like to protect the logo, etc., more closely than the documentation. I may have overshot; it's kinda restrictive, but then, I wouldn't want the logo showing up just anywhere.

### CODE REVIEW

**Comment by Wentale** [comment]
The additions read ok, Joe.

**Review by xolotl — APPROVED** [review]
Looks good! Merging...

**Comment by xolotl** [comment]
@murphyjoe and yet, it is taking me two merges, one for each PR, so maybe they are connected on a branch, but still treated as separate PRs.

**Comment by murphyjoe** [comment]
I think so. IIRC, on my repo, I wrote the new license text, merged it in my repo, made the pull request to the VC repo (from my master, I think), started a new branch for the definition, and then made a pull request to VC from my new branch.

So I think the best process might be (a) start new branches when editing different documents, (b) make pull requests from those branches only so reviewers can look at one thing at a time, (c) don't merge your own repo until PRs are resolved. 

Maybe people more familiar with version control know this (or something like it) by heart but it sounds like folks in our community will need to be taught.

**Comment by xolotl** [comment]
There's layers of complexity if one does not have commit rights to VC, so one has to fork like @murphyjoe did and issue PRs. Committers can edit directly but submit changes as PRs for review instead of committing immediately. All this is part of the reason why GH might be too much for VC, tho it definitely keeps track of what happens ;)

**Pull request merged**
